apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-multitool
  namespace: zadanie1
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: http1
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http2
      protocol: TCP
      port: 1180
      targetPort: 1180